FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update

RUN apt-get install -y build-essential software-properties-common curl

RUN apt-get install -y python3 python3-dev

# get install script and pass it to execute: 
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
# and install node 
RUN apt-get install -y nodejs

RUN apt-get install -y rsync git vim

RUN corepack enable && corepack prepare pnpm@9.15.0 --activate
RUN mkdir -p /livla/build/dumps
COPY src/package.json src/pnpm-lock.yaml /livla/
COPY src/tsconfig.json /livla/
WORKDIR /livla
RUN pnpm install --frozen-lockfile && pnpm add -g npm-check-updates pm2@latest typescript

# CMD pnpm start