// JavaScript Document
window.nasezvafahi = 'not found';
window.bangulo = "getting the dictionary";
window.bangubuild = "creating the index";
window.bangudesc = "<p><b>La Muplis</b> is a fast tool to search sentenes from <a href='http://tatoeba.org/eng' target='_blank'>Tatoeba.org</a> database in Polish and English.</p><p>- Can I use it if I lose internet access?<br>- Yes, if this happens try opening this very address from this browser.<br> It should still open. A latest version of Chrome, Safari or Firefox is required.<br>To increase the overall quality of the sentences displayed this app<br>1. includes only sentences owned by tatoeba.org users,<br>2. excludes sentences tagged as \"needs native check\".</p><span id='searchengine'><i><a href='#' title='jbo-sutysisku' onclick=\"window.external.AddSearchProvider('https://la-lojban.github.io/sutysisku/muplis-eng-pol/sisku.xml')\">Add as a search engine...</a></i></span>";
window.bangusisku='search';
window.xuzganalojudri = false;
window.muplis=true;
window.bangudecomp = 'decomposing...';
window.arrcll = {};
title="la muplis - English-Polish phrases";
siskudescr="Search la muplis, the dictionary of English and Polish sentences.";
opdescr = "A dictionary of sentences for English, Polish and other languages. Can work offline!";
titlelogo = "<span id='plise' style='height:24px;'><a id='st' href='../'><img src='../pixra/arrow-left.png' height='24' width='24'></a></span><span class='site-title' style='display: none;margin-left:10px;' id='site-title'><a id='title' href='#'><img src='../pixra/plise.png' height='16' width='16' title='lo staile poi sampu'><img src='../pixra/pelxuplise.png' height='16' width='16' title='lo staile poi na mutce cinri'><img src='../pixra/crinoplise.png' height='16' width='16' title='lo jufra poi ka&#39;e xamgu lo di&#39;i fanva'><img src='../pixra/blabiplise.png' height='16' width='16' title='lo staile poi ka&#39;e pluja'><img src='../pixra/cicnaplise.png' height='16' width='16' title='na&#39;e catni se ciska staile'><font color='#fff'>la muplis</font></a></span>";
mupliskari1 = "109,179,242";
mupliskari2 = "84,163,238";
mupliskari3 = "54,144,240";
mupliskari4 = "30,105,222";
gradpos1 = "0%";
gradpos2 = "50%";
gradpos3 = "51%";
gradpos4 = "100%";
upperdir = "../muplis.html";
window.purc = "Last searched: ";
window.lojbo = false;
favicon = '../pixra/plise.png';
icon16 = '../pixra/plise.png';
icon32 = '../pixra/plise.png';
