// JavaScript Document
window.nasezvafahi = 'not found';
window.bangulo = "ca'o cpacu lo vlaste";
window.bangubuild = "ca'o zbasu lo indice";
window.bangudesc = "<p><b>la .muplis.</b> cu sutra tutci lo nu mitysisku lo mupli pe ju'oi <a href='http://tatoeba.org/jbo' target='_blank'>Tatoeba.org</a></p><p>- .i xu mi kakne lo ka pilno la .muplis. vau va'o lo nu na ka'e kibro pilno<br>- .i ja'a go'i .i va'o lo nu kibro kakne na ku cu .e'u troci lo ka gau do lo brauzero cu cpacu lo se judri be lo me dei moi<br> .i la'a sai lo mutpapri cu tolcanci to'e ri'a nai .i lo cnino klesi be la xromium ja la'oi Safari ja la'oi Firefox cu jai sarcu lo nu pilno la .muplis.<br>.i lo tcita pe di'e ka'e sidju do lo ka jimpe fi lo ni zabna fa lo jufra<br>.i la'e zoi <img src='../pixra/plise.png' height='16' width='16' title='lo staile poi sampu'> zoi tcita lo jufra poi lo staile be tu'a ke'a cu sampu<br>.i la'e zoi <img src='../pixra/pelxuplise.png' height='16' width='16' title='lo staile poi na mutce cinri'> zoi tcita lo jufra poi lo staile be tu'a ke'a na mutce cinri<br>.i la'e zoi <img src='../pixra/crinoplise.png' height='16' width='16' title='lo jufra poi ka&#39;e xamgu lo di&#39;i fanva'> zoi tcita lo jufra poi ka&#39;e xamgu lo di&#39;i fanva<br>.i la'e zoi <img src='../pixra/blabiplise.png' height='16' width='16' title='lo staile poi ka&#39;e pluja'> zoi tcita lo jufra poi lo staile be tu'a ke'a ka'e pluja<br>.i la'e zoi <img src='../pixra/cicnaplise.png' height='16' width='16' title='na&#39;e catni se ciska staile'> zoi tcita lo jufra poi lo staile be tu'a ke'a cu na&#39;e catni<br><br>.i lo nu djica co zenba co cilre tu'a la .muplis. cu .e'u banzu lo nu vitke <a href='https://mw.lojban.org' target='_blank'>lo lojbo uitki</a>.</p><span id='searchengine'><i><a href='#' title='jbo-sutysisku' onclick=\"window.external.AddSearchProvider('https://la-lojban.github.io/sutysisku/muplis/sisku.xml')\">jmina zo'e ne tai lo sisku matra</a></i></span>";
window.bangusisku='sisku';
window.xuzganalojudri = false;
window.muplis = true;
window.bangudecomp = 'te katna';
window.arrcll = {};
title="Search for Lojban phrases - la muplis";
siskudescr="Search the dictionary of Lojban sentences la muplis.";
opdescr = "A dictionary of sentences for Lojban, English and other languages that can work offline.";
titlelogo = "<span class='site-title' style='display: none;margin-left:10px;' id='site-title'><a id='title' href='#'><img src='../pixra/plise.png' height='16' width='16' title='lo staile poi sampu'><img src='../pixra/pelxuplise.png' height='16' width='16' title='lo staile poi na mutce cinri'><img src='../pixra/crinoplise.png' height='16' width='16' title='lo jufra poi ka&#39;e xamgu lo di&#39;i fanva'><img src='../pixra/blabiplise.png' height='16' width='16' title='lo staile poi ka&#39;e pluja'><img src='../pixra/cicnaplise.png' height='16' width='16' title='na&#39;e catni se ciska staile'><font color='#fff'>la muplis</font></a></span>";
mupliskari1 = "109,179,242";
mupliskari2 = "84,163,238";
mupliskari3 = "54,144,240";
mupliskari4 = "30,105,222";
gradpos1 = "0%";
gradpos2 = "50%";
gradpos3 = "51%";
gradpos4 = "100%";
window.purc = "Last searched: ";
window.lojbo = true;
favicon = '../pixra/plise.png';
icon16 = '../pixra/plise.png';
icon32 = '../pixra/plise.png';
