#!/bin/sh
# Copyright 1992-2003 Logical Language Group Inc.
# Licensed under the Academic Free License version 2.0
# Does necessary yacc-ing to build a parser.
# Prerequisites: mkgramy

bison -d grammar.y
mv grammar.tab.c grammar.c
mv grammar.tab.h grammar.h
